### ISSUE TITLE
How to use the typo3 binary?

### ISSUE THREAD

**Issue by simonschaufi** [helhum/typo3-composer-setup#4]
I tried calling the scheduler the standard way but got an error:

`/var/www/html/vendor/typo3/cms/typo3/sysext/core/bin/typo3`

```
PHP Warning:  require(/var/www/html/vendor/typo3/cms/typo3/sysext/core/bin/../../../../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/vendor/typo3/cms/typo3/sysext/core/bin/typo3 on line 21
```

For the scheduler to work, the file `vendor/typo3/cms/vendor/autoload.php` needs to exist.

You mentioned this in the readme:

> This means no symlinks to files are required any more, not even the symlinked autoload file inside the typo3/cms package

but no description how to use the scheduler then...

**Comment by helhum** [comment]
> I tried calling the scheduler the standard way but got an error

That is not the standard way. The standard way in composer mode is `vendor/bin/typo3`


This package has no relation to how to call the scheduler from command line. In composer mode, you need to use the binary from the composer bin dir, if you use typo3 console, use the binary provided by it.
